
mqtt:
  host: localhost
  port: 1883
  client-id: mqtt-panel

http:
  bind: 0.0.0.0
  port: 8080

auth:
  users:
  - username: admin
    password: admin

logging:
  level: INFO

cache:
  root: data/cache

panels:
  - title: Rollershutter
    icon: widgets
    groups:
      - group_one

groups:
  - title: Test1
    name: group_one
    widgets:
    - title: Current State
      type: text
      subscribe: rollershutter/Test1/state
    - title: Last Command
      type: text
      subscribe: rollershutter/control/Test1
    - title: Current Percent
      type: text
      subscribe: rollershutter/Test1/percentage
