DOMAIN = "schanz_rolladen"

CONF_NAME = "name"
CONF_DEVICE = "device"
CONF_BAUDRATE = "baudrate"
CONF_TIME_OPEN = "time_open"
CONF_TIME_CLOSE = "time_close"
CONF_COMMAND_OPEN = "command_open"
CONF_COMMAND_CLOSE = "command_close"
CONF_TRANSPORT_PREFIX = "transport_prefix"
CONF_TRANSPORT_SUFFIX = "transport_suffix"
CONF_UPDATE_INTERVAL = "update_interval"

DEFAULT_NAME = "Schanz Rolladen"
DEFAULT_DEVICE = "/dev/ttyUSB0"
DEFAULT_BAUDRATE = 57600
DEFAULT_TIME_OPEN = 53.0
DEFAULT_TIME_CLOSE = 53.0
DEFAULT_COMMAND_OPEN = "P46#111010101110001010#R10"
DEFAULT_COMMAND_CLOSE = "P46#111010101110001000#R10"
DEFAULT_TRANSPORT_PREFIX = "sendMsg "
DEFAULT_TRANSPORT_SUFFIX = "\n"
DEFAULT_UPDATE_INTERVAL = 0.2

