version: '2.3'
services:
  schanz-rolladen-mqtt:
    image: ghcr.io/8ch9azbsfifz/schanz-rolladen-raspi:latest
    restart: always
    environment:
      MQTT_HOST: t20
      MQTT_PORT: 1883
      USEFHEM: "False"
      USERELAIS: "True"
      PIN_BCM_UP: 23
      PIN_BCM_DOWN: 24
      TIME_OPEN: 53
      TIME_CLOSE: 53
      ROLLERSHUTTER_NAME: Test1
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
