mqtt:
  - cover:
      name: "MQTT Cover"
      command_topic: "rollershutter/control/Test1"
      set_position_topic: "rollershutter/control_position/Test1"
      payload_open: "Open"
      payload_close: "Close"
      payload_stop: "Stop"
      #state_topic: "rollershutter/state/Test1"
      #state_open: "open"
      state_opening: "opening"
      #state_closed: "closed"
      state_closing: "closing"
      optimistic: false
      value_template: "{{ value.x }}"
      position_template: "{{ value.y }}"
      position_topic: "rollershutter/Test1/percentage"
      position_open: 0
      position_closed: 100

