version: '2.2'

services:
  mqtt:
    restart: unless-stopped
    image: eclipse-mosquitto:1.6 # 2.0 breaking change address error
    ports:
      - "1883:1883"
      - "9001:9001"
  dashboard:
    restart: unless-stopped
    image: sourcesimian/mqtt-panel:latest
    ports:
      - "8080:8080"
    volumes:
      - "./config.yaml:/config.yaml"
